languages:
  JavaScript: true
engines:
  csslint:
    enabled: true
  eslint:
      enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - JavaScript
ratings:
  paths:
  - "**.css"
  - "**.js"